= REST API Guide
portfolio-won;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-http-request-title: Example request
:operation-http-response-title: Example response
:favicon: /favicon.ico
[[overview]]

= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

//| `200 No Content`
//| 기존 리소스를 성공적으로 수정함.

| `410 Gone`
| 기존 리소스를 성공적으로 삭제함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===

[[user-resources]]
== USER RESOURCE

사용자에 대한 API 정의 및 설명이다.

[[user-create-resources]]
=== Create User

`POST` 요청으로 사용자를 생성할 수 있다.

operation::create-users[snippets='request-headers,request-fields,request-body,http-request,httpie-request,curl-request,response-headers,response-fields,links,response-body,http-response']

[[user-list-resources]]
=== List User

`GET` 요청으로 회원에 대한 목록을 볼 수 있다.

operation::list-users[snippets='request-headers,request-parameters,http-request,httpie-request,curl-request,response-headers,response-fields,links,response-body,http-response']

[[blog-reseources]]
== BLOG RESOURCE

[[blog-create-resources]]
=== Create Blog

`POST` 요청으로 블로그를 생성할 수 있다.

operation::create-blogs[snippets='request-headers,request-fields,request-body,http-request,httpie-request,curl-request,response-headers,response-fields,links,response-body,http-response']

[[blog-list-resources]]
=== List Blog

`GET` 요청으로 블로그의 목록을 가져올 수 있다.

operation::list-blogs[snippets='request-headers,request-parameters,http-request,httpie-request,curl-request,response-headers,response-fields,links,response-body,http-response']

[[blog-read-resources]]
=== Read Blog

`GET` 요청으로 특정한 블로그에 대한 정보를 가져올 수 있다.

operation::read-blogs[snippets='request-headers,path-parameters,http-request,httpie-request,curl-request,response-headers,response-fields,links,response-body,http-response']

[[blog-update-resources]]
=== Update Blog

`PUT` 요청으로 특정한 블로그에 대한 정보를 수정을 할 수 있다.

현재 API를 사용할 수 있는 사용자는 블로그를 작성한 당사자와 관리자만 사용이 가능하다.

[[blog-update-slice-resources]]

`PATCH` 요청으로 특정한 블록의 일 부분을 수정을 할 수 있다.

현재 API를 사용할 수 있는 사용자는 블로그를 작성한 당사자와 관리자만 사용이 가능하다.

[[replies-create-resources]]
=== Create Blog Reply

`POST` 요청으로 특정한 블로그에 Reply을 추가할 수 있다.

operation::create-replies[snippets='request-headers,path-parameters,http-request,,curl-request,response-headers,response-fields,links,response-body,http-response']

[[study-reseources]]
== STUDY RESOURCES

[[study-create-resources]]
=== Create Study

`POST` 요청으로 새로운 스터디 모임을 생성할 수 있다.

[[study-find-resources]]
=== Find Study

`GET` 요청으로 현재 서비스에서 등록이 되어 있는 스터디를 찾을 수 있다.

[[study-update-resources]]
=== Update Study

`PUT` 요청으로 현재 서비스에 등록된 스터디를 변경이 가능하다.

현재 API를 사용할 수 있는 사용자는 스터디를 생성한 사람 및 관리자만 사용이 가능하다.


[[study-part-update-resources]]
=== Update Study

`PATCH` 요청으로 현재 서비스에 등록된 스터디의 일 부분을 변경이 가능하다.

현재 API를 사용할 수 있는 사용자는 스터디를 생성한 사람 및 관리자만 사용이 가능하다.

현재 스터디의 상테를 변경하기 위해서 사용이 된다.


[[study-delete-resources]]
=== Delete Study

`DELETE` 요청으로 현재 서비스에 등록이된 스터디를 삭제가 가능하다.

삭제가 가능한 스터디는 현재 종료가 되어 있는 스터디이거나, 스터디를 주최한 주최자 혹은 사이트의 관리자만 가능하다.

