-- MySQL Script generated by MySQL Workbench
-- Wed Oct 26 13:25:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tbl_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_user` (
  `email` VARCHAR(45) NOT NULL COMMENT '* 사용자의 이메일 \n',
  `password` VARCHAR(50) NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT '사용자의 이름\n',
  `token` VARCHAR(255) NULL COMMENT '비밀번호 분실시 찾기 위한 token 값 ',
  `user_active` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `udpated_at` DATETIME NOT NULL DEFAULT now(),
  `join_time` DATETIME NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_user_role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_user_role` (
  `tbl_user_email` VARCHAR(45) NOT NULL,
  `user_role` ENUM('ADMIN', 'MANAGER', 'CUSTOMER') NOT NULL DEFAULT 'CUSTOMER',
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NOT NULL DEFAULT now(),
  INDEX `fk_tbl_user_role_tbl_user_idx` (`tbl_user_email` ASC),
  CONSTRAINT `fk_tbl_user_role_tbl_user`
    FOREIGN KEY (`tbl_user_email`)
    REFERENCES `mydb`.`tbl_user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_user_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_user_profile` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_user_profile` (
  `tbl_user_email` VARCHAR(45) NOT NULL,
  `profile_image` VARCHAR(255) NULL,
  INDEX `fk_tbl_user_profile_tbl_user1_idx` (`tbl_user_email` ASC),
  CONSTRAINT `fk_tbl_user_profile_tbl_user1`
    FOREIGN KEY (`tbl_user_email`)
    REFERENCES `mydb`.`tbl_user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_user_profile_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_user_profile_history` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_user_profile_history` (
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_user_setting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_user_setting` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_user_setting` (
  `tbl_user_email` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NOT NULL DEFAULT now(),
  INDEX `fk_tbl_user_setting_tbl_user1_idx` (`tbl_user_email` ASC),
  CONSTRAINT `fk_tbl_user_setting_tbl_user1`
    FOREIGN KEY (`tbl_user_email`)
    REFERENCES `mydb`.`tbl_user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_user_setting_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_user_setting_history` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_user_setting_history` (
)
ENGINE = InnoDB;

USE `mydb`;

DELIMITER $$

USE `mydb`$$
DROP TRIGGER IF EXISTS `mydb`.`tbl_user_profile_BEFORE_UPDATE` $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`tbl_user_profile_BEFORE_UPDATE` BEFORE UPDATE ON `tbl_user_profile` FOR EACH ROW
BEGIN
	insert into `mydb`.`tbl_user_profile_history` value() ;
END$$


USE `mydb`$$
DROP TRIGGER IF EXISTS `mydb`.`tbl_user_profile_BEFORE_DELETE` $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`tbl_user_profile_BEFORE_DELETE` BEFORE DELETE ON `tbl_user_profile` FOR EACH ROW
BEGIN
	insert into `mydb`.`tbl_user_profile_history` value() ;
END$$


USE `mydb`$$
DROP TRIGGER IF EXISTS `mydb`.`tbl_user_setting_BEFORE_UPDATE` $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`tbl_user_setting_BEFORE_UPDATE` BEFORE UPDATE ON `tbl_user_setting` FOR EACH ROW
BEGIN
	INSERT INTO `mydb`.`tbl_user_setting_history` VALUES();
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
